import { Car } from '../types';

export const useCars = () => {
  const cars: Car[] = [
    {
      id: 1,
      make: 'Porsche',
      model: '911 Carrera',
      year: 2023,
      type: 'Coupe',
      category: 'Sport',
      seats: 4,
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      pricePerDay: 450,
      imageUrl: 'https://images.pexels.com/photos/3729464/pexels-photo-3729464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Leather Seats', 'Bose Sound System', 'Sport Chrono Package', 'Sunroof'],
    },
    {
      id: 2,
      make: 'Mercedes-Benz',
      model: 'G-Class',
      year: 2024,
      type: 'SUV',
      category: 'SUV',
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      pricePerDay: 550,
      imageUrl: 'https://images.pexels.com/photos/1637859/pexels-photo-1637859.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Heated Seats', '360° Camera', 'Ambient Lighting', 'Burmester Sound System'],
    },
    {
      id: 3,
      make: 'Tesla',
      model: 'Model S Plaid',
      year: 2024,
      type: 'Sedan',
      category: 'Electric',
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Electric',
      pricePerDay: 400,
      imageUrl: 'https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Autopilot', '17" Touchscreen Display', 'Glass Roof', 'Premium Audio'],
    },
    {
      id: 4,
      make: 'BMW',
      model: 'M4 Competition',
      year: 2023,
      type: 'Coupe',
      category: 'Sport',
      seats: 4,
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      pricePerDay: 420,
      imageUrl: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Carbon Fiber Trim', 'Harman Kardon Audio', 'M Sport Seats', 'Laserlight Headlights'],
    },
    {
      id: 5,
      make: 'Range Rover',
      model: 'Sport',
      year: 2023,
      type: 'SUV',
      category: 'SUV',
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Hybrid',
      pricePerDay: 480,
      imageUrl: 'https://images.pexels.com/photos/3764014/pexels-photo-3764014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Air Suspension', 'Meridian Sound System', 'Panoramic Roof', 'Heated Steering Wheel'],
    },
    {
      id: 6,
      make: 'Audi',
      model: 'R8 Spyder',
      year: 2023,
      type: 'Convertible',
      category: 'Sport',
      seats: 2,
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      pricePerDay: 650,
      imageUrl: 'https://images.pexels.com/photos/627678/pexels-photo-627678.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['V10 Engine', 'Bang & Olufsen Sound', 'Virtual Cockpit', 'Carbon Fiber Accents'],
    },
     {
      id: 7,
      make: 'Lamborghini',
      model: 'Urus',
      year: 2024,
      type: 'SUV',
      category: 'SUV',
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      pricePerDay: 700,
      imageUrl: 'https://images.pexels.com/photos/3972755/pexels-photo-3972755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Active Air Suspension', 'Akrapovič Exhaust', 'Alcantara Interior', 'Night Vision'],
    },
    {
      id: 8,
      make: 'Rolls-Royce',
      model: 'Cullinan',
      year: 2024,
      type: 'SUV',
      category: 'Luxury',
      seats: 5,
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      pricePerDay: 950,
      imageUrl: 'https://images.pexels.com/photos/10394782/pexels-photo-10394782.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Starlight Headliner', 'Champagne Cooler', 'Magic Carpet Ride Suspension', 'Bespoke Audio'],
    },
     {
      id: 9,
      make: 'Bentley',
      model: 'Continental GT',
      year: 2024,
      type: 'Coupe',
      category: 'Luxury',
      seats: 4,
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      pricePerDay: 850,
      imageUrl: 'https://images.pexels.com/photos/3354648/pexels-photo-3354648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      features: ['Diamond Quilted Seats', 'Naim for Bentley Audio', 'Rotating Display', 'Air Suspension'],
    },
  ];

  return { cars };
};